## utak atik

no_metadata = true
# num_repeats = 8
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
# clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
# epoch = 2
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 80.0
highvram = true
huber_c = 1.1
huber_schedule = "snr"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 1.1
loss_type = "huber"
lr_scheduler = "cosine"
max_data_loader_n_workers = 2
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 800
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 160
network_args = ["conv_dim=4", "conv_alpha=4"]
network_dim = 160
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args =  ["d_coef=2", "use_bias_correction=True", "decouple=True"]  
optimizer_type = "Prodigy"
output_dir = "/app/outputs"
output_name = "last"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 10
save_model_as = "safetensors"
save_precision = "float"
scale_weight_norms = 5
seed = 42
train_batch_size = 4
training_comment = ""
xformers = true
